databases:
  - name: shortify-db
    plan: free
    databaseName: shortify
    user: shortify_user

services:
  # 1. Backend (Spring Boot Dockerized Web Service)
  - type: web
    name: shortify-backend
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SQL_HOST}:${SQL_PORT}/${SQL_NAME}
      - key: SQL_HOST
        fromDatabase:
          name: shortify-db
          property: host
      - key: SQL_PORT
        fromDatabase:
          name: shortify-db
          property: port
      - key: SQL_NAME
        fromDatabase:
          name: shortify-db
          property: database
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: shortify-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: shortify-db
          property: password
      - key: JWT_SECRET
        generateValue: true

  # 2. Frontend (Vite Static Site)
  - type: web
    name: shortify-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
