# Server Configuration
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/shortify_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hk@202005}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
jwt.secret=${JWT_SECRET:h4v3y0u3v3rh34rdt4h3tr4g3dy0fd4rthpl4gu315t4h3w1530n3th4t5n0t45t0ryth3j3d1w0uld73lly0u}
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
