# Server Configuration
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/shortify_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=hk@202005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Security Configuration
jwt.secret=h4v3y0u3v3rh34rdt4h3tr4g3dy0fd4rthpl4gu315t4h3w1530n3th4t5n0t45t0ryth3j3d1w0uld73lly0u
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
